### ISSUE TITLE
Include fastd section of the announced data

### ISSUE THREAD

**Issue by ghost** [dereulenspiegel/node-collector#10]
I need the fastd section for a better implementation of https://github.com/ffnord/meshviewer/pull/10. 
Can you add them here while I try to get them into the ffmap-backend? We can also wait for it to be done in ffmap-backend. The format just has to be clear.

**Comment by dereulenspiegel** [comment]
You mean to include the facts about fastd version and whether it is enabled or not in the output generated for meshviewer? As soon as I know how to include this into the generated output this should be easy. But this probably a new output format?

**Comment by dereulenspiegel** [comment]
To implement this, I would need a specification or at least an example how the nodes.json with fastd data should look like.

**Comment by ghost** [comment]
I'm waiting for tcatm to do this or reject it in ffmap-backend
So this is just at some time in the future

**Comment by ghost** [comment]
So the output should look like [this](http://map.ffdus.de/data/nodes.json)
Specification: Copy the mesh_vpn object from the statistics data 1:1
Are you at 32C3?

**Comment by dereulenspiegel** [comment]
I am currently at the Freifunk Assembly for some time.
Currently announced in the current stable release of gluon doesn't seem to send the required information. I will prepare the necessary structures for the legacy output, but I will need to see what announced is sending.

**Comment by dereulenspiegel** [comment]
Solved at 32C3 in a better way.
