### ISSUE TITLE
gluon-collector: multiple instances?

### ISSUE THREAD

**Issue by ghost** [dereulenspiegel/node-collector#22]
I want to run multiple instances. If I start the second instance, it kills the first one.

**Comment by dereulenspiegel** [comment]
You can use mutliple receiver to run on multiple batman interfaces. Otherwise it should be sufficient to change the server port the collector listens on for responses, path to database etc. so two instances don't conflict.

**Comment by ghost** [comment]
I just got it to work. It was a very stupdid mistake in a script..
